version: '3.0'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      # - TZ=Europe/Brussels
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:9000/tcp"
    restart: always
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      # - TZ=Europe/Brussels
      - CLI_ARGS= #optional
    volumes:
      - /opt/duplicati/config:/config
      - /opt:/source
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8200:8200
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
      # - TZ=Europe/Brussels
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/log:/mosquitto/log
      - /opt/mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
      - 9001:9001
  # zigbee2mqtt:
  #   image: koenkk/zigbee2mqtt
  #   container_name: zigbee2mqtt
  #   depends_on:
  #     - mosquitto
  #   volumes:
  #     - /opt/zigbee2mqtt/data:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
  #   devices:
  #     - /dev/ttyUSB0 #TODO: use correct device name! EG /dev/ttyUSB0:/dev/ttyUSB0
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    environment:
      # - TZ=Europe/Brussels
      - DECONZ_WEB_PORT=8900
      - DECONZ_WS_PORT=8901
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_UID=0
      - DECONZ_GID=0
      - DECONZ_START_VERBOSE=0
    volumes:
      - /opt/deconz:/opt/deCONZ
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8900:8900
      - 8901:8901
    restart: always
    privileged: true
    devices:
      - /dev/ttyUSB0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"